language: swift
osx_image: xcode9.2
cache:
  - cocoapods
before_install:
  - gem install cocoapods
  - gem install fastlane
script:
  # Output something every 10 minutes or Travis kills the job
  - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - fastlane beta
  # Killing background sleep loop
  - kill %1
branches:
  only:
    - master
