language: swift
osx_image: xcode10.2
cache:
  - cocoapods
before_install:
  - gem install cocoapods
  - gem install fastlane
  - pod repo update
script:
  # Output something every 10 minutes or Travis kills the job
  - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - fastlane beta_fabric
  # - fastlane beta_testflight
  # Killing background sleep loop
  - kill %1
branches:
  only:
    - master
