language: swift
osx_image: xcode9.2
cache:
  - cocoapods
before_install:
  - gem install cocoapods
  - gem install fastlane
  - pod repo update
  - pod install
script:
  - travis_wait 30 fastlane beta
