fastlane_version '2.70.3'

default_platform :ios

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta_fabric do |values|
    if ENV['CI'] == 'true'
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV['MATCH_KEYCHAIN_PASSWORD'],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
    end
    match(
      type: 'adhoc',
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      readonly: true
    )

    # CocoaPods
    # cocoapods repo_update: true

    # Increment build number
    build_number = ENV['TRAVIS_BUILD_NUMBER']
    if build_number.nil?
      # TODO: Do something about this.
      # We need to somehow increase the build number.
      puts "There is no travis build number. #{build_number}"
      increment_build_number
    else
      puts "Current travis build number is #{build_number}"
      increment_build_number build_number: build_number
    end
    # Fabric specific
    bn = get_build_number
    set_info_plist_value(path: './Ballet/Resources/Info.plist', key: 'CFBundleVersion', value: bn)

    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution
    # uses ad-hoc provisioning
    build_app(scheme: 'Ballet', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : nil
    groups = values[:test_group] ? values[:test_group] : ['Developers']

    crashlytics(
      api_token: ENV['FABRIC_API_TOKEN'],
      build_secret: ENV['FABRIC_BUILD_SECRET'],
      emails: emails,
      groups: groups,
      notes: changelog_from_git_commits,
      notifications: true
    )

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end

  lane :beta_testflight do |values|
    if ENV['CI'] == 'true'
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV['MATCH_KEYCHAIN_PASSWORD'],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
    end
    match(
      type: 'appstore',
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      readonly: true
    )

    # CocoaPods
    # cocoapods repo_update: true

    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    bn = get_build_number
    set_info_plist_value(path: './Ballet/Resources/Info.plist', key: 'CFBundleVersion', value: bn)

    build_app(scheme: 'Ballet', export_method: 'app-store')

    # Testflight
    upload_to_testflight
  end
end
